name: StrayBullet
favicon: null
layout_spectrum: 0.4122441108338535
typography_spectrum: 0.8657005182467401
title: Stray Bullet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9073868626728654
  lightness: 0.7805882287211716
  saturation: 0.7660000098403543
  rhythmicContrast: 0.17503876774571836
purpose: []
