name: StrayBullet
favicon: null
layout_spectrum: 0.91139
typography_spectrum: 0.30693
title: Stray Bullet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000e42'
    - '#d3d5de'
    - '#636b8b'
    - '#a7acbe'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
